import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { resolve } from 'path'

// The sitemap is generated by scripts/gen-sitemap.mjs (run after `vite build` in
// build:prerender) — the single source of truth, with trailing slashes, <lastmod>
// and reciprocal ES↔EN hreflang alternates. No build-time plugin (it emitted a
// second, worse sitemap: /404 included, no slashes, no alternates).

// https://vite.dev/config/
export default defineConfig({
  plugins: [
    react(),
  ],
  resolve: {
    alias: {
      '@': resolve(__dirname, 'src'),
    },
  },
  server: {
    historyApiFallback: true,
    // Allows temporary review tunnels (localhost.run / Cloudflare) without deploying.
    allowedHosts: true,
  },
  build: {
    rollupOptions: {
      output: {
        manualChunks(id) {
          if (id.includes('node_modules/react') || id.includes('node_modules/react-dom') || id.includes('node_modules/react-router-dom')) {
            return 'react-vendor'
          }
          if (id.includes('node_modules/react-markdown') || id.includes('node_modules/remark-gfm')) {
            return 'markdown'
          }
          if (id.includes('node_modules/gsap')) {
            return 'animations'
          }
        },
      },
    },
  },
})
